name: 'Monthly Merge test'

on:
  schedule:
  # I am using the monthly cron job to run the nightly merge github action
  # in order to reduce custom code.
  # This will ensure that this action runs only once
    - cron:  '0 0 1 * *'

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Monthly merge
      uses: robotology/gh-action-nightly-merge@v1.3.2
      with:
        stable_branch: 'archive'
        development_branch: 'main'
        allow_ff: false
      env:
        GITHUB_TOKEN: "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"
