name: 'Monthly Merge'
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
#   schedule:
#     - cron:  '0 0 1 * *'
  
jobs:
   nightly-merge:

    runs-on: ubuntu-latest

    steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#         ref: archive
#         token: ${{ secrets.ACTION_TOKEN }}
      
#     - name: Monthly merge
#       uses: robotology/gh-action-nightly-merge@v1.3.2

#       with:
#         stable_branch: 'main'
#         development_branch: 'archive'
#         allow_forks: true
#         allow_ff: true
      
    - name: Checkout 2
      uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.ACTION_TOKEN }}
    - run: |
          cd ..
          rm -rf ucast-db-test
          git config user.name  'phanicode'
          git config user.email 'phaniv@email.arizona.edu'
          git clone https://github.com/phanicode/ucast-db-test.git
          
          cd ucast-db-test
          git checkout archive
          git merge main -m "merging main"
          Y=$(date -d "12 hours ago" '+%Y')
          m=$(date -d "12 hours ago" '+%m')
          d=$(date -d "12 hours ago" '+%d')
          echo $Y $m $d
          echo ALMA/$Y-$m
          git checkout main
          git rm --ignore-unmatch ALMA/$Y-$m* 
          git rm --ignore-unmatch APEX/$Y-$m*
          git rm --ignore-unmatch GLT/$Y-$m*
          git rm --ignore-unmatch JCMT/$Y-$m*
          git rm --ignore-unmatch KP/$Y-$m*
          git rm --ignore-unmatch LMT/$Y-$m*
          git rm --ignore-unmatch PDB/$Y-$m*
          git rm --ignore-unmatch PV/$Y-$m*
          git rm --ignore-unmatch SMA/$Y-$m*
          git rm --ignore-unmatch SMT/$Y-$m*
          git rm --ignore-unmatch SPT/$Y-$m*
          git add .
          
          git commit -m --allow-empty "removed last month" 
          git push --force --set-upstream origin
          
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
