name: 'Monthly Merge'
on: [push]

#   schedule:
#     - cron:  '0 0 1 * *'
  
jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Monthly merge
      uses: robotology/gh-action-nightly-merge@v1.3.2
      with:
        stable_branch: 'devel'
        development_branch: 'master'
        allow_ff: false
        
    
      env:
        GITHUB_TOKEN: "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"
    - run: |
          Y=$(date +%Y)
          m=$(date +%m)
          ls
          echo Y
          echo m
          echo ALMA/$Y-$m
          git remote set-url origin "https://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@https://github.com/phanicode/ucast-db-test.git"
          git config user.name  'phanicode'
          git config user.email 'phaniv@email.arizona.edu'
          git checkout main
          git rm ALMA/$Y-$m*
          git add .
          git commit -m  "removed last month"
          git push --force --set-upstream origin
          
          

    
