name: 'Monthly Merge'
on: [push]

#   schedule:
#     - cron:  '0 0 1 * *'
  
jobs:
   nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
      with:
        ref: archive 
        token:  ${{ secrets.ACTION_TOKEN }}
    - name: Monthly merge
      uses: robotology/gh-action-nightly-merge@v1.3.2
      with:
        stable_branch: 'archive'
        development_branch: 'main'
        allow_ff: false
        allow_forks: true

      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      
  


